name: Deploy Vinea

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: .build/package-lock.json

      - run: echo "step 1 OK"

      - name: Install
        run: npm ci --prefix .build

      - run: echo "step 2 OK"

      - name: Build
        run: node .build/build.mjs

      - run: echo "step 3 OK"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./vendor
          force_orphan: true
          commit_message: test deploy
